services:
  - type: web
    name: stella-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: prefix
        sync: false
      - key: token
        sync: false
      - key: weatherapikey
        sync: false
      - key: textgearapikey
        sync: false
      - key: mongoUri
        sync: false
